services:
    redis-master:
        container_name: redis-master
        image: redis:latest
        command: redis-server /data/conf/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - ./conf/redis.conf/:/data/conf/redis.conf:rw
            - ./data/:/data/:rw

    redis-slave:
        image: redis:latest
        command: redis-server /data/conf/redis.conf --slaveof redis-master 6379
        volumes:
            - ./conf/redis.conf/:/data/conf/redis.conf:rw
            


